version: 2

models:
    - name: raw_fixtures
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: raw_teams
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: raw_venues
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

sources:
  - name: football_api_data
    description: "data from football api containing information about ligue a "
    database: mrge-406006
    schema: raw_api_football
    tables:
      - name: fixtures
        description: "holds match information"
      - name: teams
        description: "holds information about clubs"
