name: Setup Gcloud Env
run-name: ${{ github.actor }} is setting up gcloud
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    #grant permissions to created a tokenfile in order to use workload identity pools of github for authentication
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # authenticate against gcloud https://github.com/google-github-actions/setup-gcloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/343329432514/locations/global/workloadIdentityPools/github-actions'
        service_account: 'mrge-workload-identity@mrge-406006.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'create-dbt-service-account'
      run: 'gcloud iam service-accounts create dbt-480'
    - name: 'provision-dbt-service-account-rights'
      run: 'gcloud iam service-accounts create dbt-480'
    - name: 'create-bq-dataset-raw-api-football'
      run: 'bq --location=EU mk -dataset raw_api_football'

